<a href="https://colab.research.google.com/github/Joshmen06/Project_data/blob/main/Project_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
kag_data='/content/KAG_Conversion_Data.csv'
data=np.genfromtxt(kag_data,delimiter=',',skip_header=1,encoding=None,dtype=str)
data


array([['708746', '916', '103916', ..., '1.429999948', '2', '1'],
       ['708749', '916', '103917', ..., '1.820000023', '2', '0'],
       ['708771', '916', '103920', ..., '0', '1', '0'],
       ...,
       ['1314412', '1178', '179979', ..., '40.28999949', '2', '0'],
       ['1314414', '1178', '179981', ..., '198.7100005', '8', '2'],
       ['1314415', '1178', '179982', ..., '165.6099987', '5', '2']],
      dtype='<U11')

In [23]:
data_float=np.genfromtxt(kag_data,delimiter=',',skip_header=1,encoding=None,dtype=float)
data_float

array([[7.08746000e+05, 9.16000000e+02, 1.03916000e+05, ...,
        1.42999995e+00, 2.00000000e+00, 1.00000000e+00],
       [7.08749000e+05, 9.16000000e+02, 1.03917000e+05, ...,
        1.82000002e+00, 2.00000000e+00, 0.00000000e+00],
       [7.08771000e+05, 9.16000000e+02, 1.03920000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.31441200e+06, 1.17800000e+03, 1.79979000e+05, ...,
        4.02899995e+01, 2.00000000e+00, 0.00000000e+00],
       [1.31441400e+06, 1.17800000e+03, 1.79981000e+05, ...,
        1.98710001e+02, 8.00000000e+00, 2.00000000e+00],
       [1.31441500e+06, 1.17800000e+03, 1.79982000e+05, ...,
        1.65609999e+02, 5.00000000e+00, 2.00000000e+00]])

In [13]:
xyz_camp=data[:,1]
np.unique(xyz_camp)


array(['1178', '916', '936'], dtype='<U11')

In [14]:
unique_id, count = np.unique(xyz_camp,return_counts=True)
print(unique_id)
print(count)

['1178' '916' '936']
[625  54 464]


In [15]:
for i in range(len(unique_id)):
  print('{} ran {} times'.format(unique_id[i],count[i]))

1178 ran 625 times
916 ran 54 times
936 ran 464 times


In [16]:
age=data[:,3]
age

array(['30-34', '30-34', '30-34', ..., '45-49', '45-49', '45-49'],
      dtype='<U11')

In [18]:
age_unique=np.unique(age)
print("The different age groups :")
age_unique


The different age groups :


array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11')

In [24]:
spent=data_float[:,8]
spent

array([  1.42999995,   1.82000002,   0.        , ...,  40.28999949,
       198.7100005 , 165.6099987 ])

In [25]:
avg_spent=spent.mean()
avg_spent

51.36065613141295

In [26]:
spent_min=spent.min()
spent_min

0.0

In [27]:
spent_max=spent.max()
spent_max

639.9499981

In [28]:
click=data_float[:,7]
Id=data_float[:,0]
print(Id)
click

[ 708746.  708749.  708771. ... 1314412. 1314414. 1314415.]


array([  1.,   2.,   0., ...,  28., 135., 114.])

In [29]:
max_click=click.max()
max_click

421.0

In [30]:
print('Id having maximum number of clicks',Id[click==421])

Id having maximum number of clicks [1121814.]


In [31]:
approved_conv=data_float[:,10]
approved_conv

array([1., 0., 0., ..., 0., 2., 2.])

In [32]:
print('Total people bought the product after seeing the ad with most clicks',approved_conv[click==421])

Total people bought the product after seeing the ad with most clicks [13.]


In [34]:
max_purchase=approved_conv.max()
max_purchase

21.0

In [35]:
if max_purchase > 13:
  print('No, It is not the max number of purchases in the dataset ')
else:
  print('Yes , it is the max number of purchases in the dataset') 

No, It is not the max number of purchases in the dataset 


In [36]:
data_float[approved_conv==21]

array([[1.12110400e+06, 1.17800000e+03, 1.44533000e+05,            nan,
                   nan, 1.60000000e+01, 2.08066600e+06, 2.02000000e+02,
        3.60150001e+02, 4.00000000e+01, 2.10000000e+01]])